name: Hakalle CI Workflow

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build latest Hakalle source
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
    
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Build Hakalle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: shadowJar
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload Hakalle jar
        uses: actions/upload-artifact@v3
        with:
          name: hakalle
          path: hakalle/build/libs/hakalle-0.1-all.jar
